home/urls.py
from django.urls import path
from .views import HomeView

app_name = "home"
urlpatterns = [
    path('', HomeView.as_view(), name="home_view"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('contact.urls')),
    path('', include('about.urls')),
    path('', include('products.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import ProductsView, ProductView

app_name = "products"
urlpatterns = [
    path('products/', ProductsView.as_view(), name="products_view"),
    path('products/details/<int:product_id>/', ProductView.as_view(), name="product_view")
]

products/models.py
from django.db import models
from category.models import Category
from django.utils.text import slugify

class Product(models.Model):
    title = models.CharField(
        max_length=200, 
        help_text="Enter the product title. Make it descriptive and unique."
    )
    short_desc = models.TextField(
        max_length=400, 
        blank=True, 
        help_text="Enter a brief description of the product (max 400 characters)."
    )
    # desc = models.TextField(
    #     max_length=2000, 
    #     help_text="Enter a detailed description of the product (max 2000 characters)."
    # )
    image = models.ImageField(
        upload_to="products/", 
        blank=True, 
        null=True, 
        help_text="Upload a product image. Recommended size: 800x800px."
    )
    # price = models.FloatField(default=0.0, help_text="Enter product price.")
    categories = models.ManyToManyField(
        Category, 
        related_name="products", 
        help_text="Select one or more categories for the product."
    )
    slug = models.SlugField(
        max_length=255, 
        unique=True, 
        blank=True, 
        help_text="Slug for the product URL. Leave blank to auto-generate."
    )
    is_featured = models.BooleanField(
        default=False, 
        help_text="Mark as featured to highlight this product."
    )
    created_at = models.DateTimeField(
        auto_now_add=True, 
        help_text="The date and time when the product was created."
    )
    updated_at = models.DateTimeField(
        auto_now=True, 
        help_text="The date and time when the product was last updated."
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Automatically generate a slug if not provided
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

products/views.py
from django.shortcuts import render
from .models import Product, Category
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
# Create your views here.

class ProductsView(ListView):
    template_name = "products/products.html"
    ordering = ['updated_at']
    model = Product
    context_object_name = "products"

    def get_queryset(self):

        qs = super().get_queryset()
        category_id = self.request.GET.get("category_id")

        if category_id:
            category = get_object_or_404(Category, pk=int(category_id))
            qs = category.products.all().order_by("created_at")
        
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by("updated_at")
        return context

# product details view
class ProductView(DetailView):
    template_name = "products/product_details.html"
    model = Product
    context_object_name = "product_details"


    def get_object(self, queryset = None):
        product_id = self.kwargs['product_id']
        return get_object_or_404(self.model, pk=product_id)

products/templates/products/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Honodic - Home
{% endblock %}

{% block stylesheets %}
  
{% endblock %}






{% block content %}
    {% include 'navbars/default_navbar.html' %}

    <section class="py-5">
        <div class="container mx-auto py-3">
           <div class="row">
                <div class="col-md-6 col-12">
                    <img src="{{product_details.image.url}}" alt="{{product_details.title}}" width="490px" height="400px" class="rounded-1" >
                </div>

                <div class="col-md-6 col-12">
                    {% if product_details.is_featured %}
                        <div class="py-1 px-2 rounded-2 border border-2 align-content-center border-success">
                            <h5>Featured product</h5>
                        </div>
                    {% endif %}

                    <h2>{{product_details.title}}</h2>
                    {% comment %} <h3>Price: {{product_details.price}}</h3> {% endcomment %}
                    <p>
                        {{product_details.short_desc}}
                    </p>
                </div>

            </div>

            {% comment %} <div class="py-4">
                <p>
                    {{product_details.desc}}
                </p>
            </div> {% endcomment %}
        </div>
    </section>
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Honodic - Home
{% endblock %}

{% block stylesheets %}
    <link href="{% static 'products/css/products.css' %}" rel="stylesheet"></link>

    <style>
        .product__hero {
            height: 350px;
            background: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.4)),
                    url({% static 'products/images/products_hero_image.jpg' %}) no-repeat center/cover;"
        }

        .search__field {
            background-color: transparent;
            border: none;
            outline: none;
            width: 100%;
        }

        .search__btn {
            background-color: #13E26A;
            color: black;
            border-radius: 30px;
            width: 20%;
        }

        .search_box_container {
            border: 1px solid white;
            border-radius: 30px;
            background-color: white;
            width: 40%;
            height: 40px;
            padding: 0px 0px 0px 20px;
        }

        @media only screen and (max-width: 991px) {
            .search_box_container {
                border: 1px solid white;
                border-radius: 30px;
                background-color: white;
                width: 97%;
                height: 40px;
                padding: 0px 0px 0px 20px;
            }
        }
    </style>
{% endblock %}



{% block content %}
    {% include 'navbars/default_navbar.html' %}

    {% comment %} hero section {% endcomment %}
    <section class="product__hero py-5 justify-content-center align-content-center">
        <div class="container py-4">
            <h1 class="text-center text-white">All Products</h1>
            {% comment %} search bar {% endcomment %}
            <div class="d-flex search_box_container justify-content-between m-auto">
                <input class="search__field" type="search" name="search" id="search" placeholder="Search">
                <button class="search__btn" type="submit">Search</button>
            </div>
        </div>
    </section>

    {% comment %} categories {% endcomment %}
    <section class="py-5">
        <div class="container mx-auto">
            <div class="row">
                <div class="col-lg-2">
                    <h3>All Catehories</h3>
                    <ul class="rounded-2 p-2">
                        <li>
                            <a class="py-0 my-0" href="{% url 'products:products_view' %}">All products</a>
                        </li>
                        {% for category in categories %}
                            <li>
                                <a class="py-0 my-0" href="{% url 'products:products_view' %}?category_id={{category.id}}">{{category.title}}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-10">
                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-3 col-md-4 col-12">
                                <div class="card shadow-sm featured_product_card" >
                                   
                                    <img width="400px" height="400px" src="{{product.image.url}}" class="card-img-top" alt="Delicious Food">
                            
                                    <div class="card-body text-center">
                                        <h5 class="card-title">{{product.title}}</h5>
                                        <p class="card-text text-muted">{{product.short_desc|slice:":60"}}..</p>
                                        <div class="row">
                                          
                                            <div class="col-12">
                                                <a href="{% url 'products:product_view' product.id %}" class="btn btn-outline-success btn-sm w-100">View Now</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}